### ISSUE TITLE
When failing to auth against a feed, you never get another chance to retry auth'ing. Even after reboot it keeps on failing.

### ISSUE THREAD

**Issue by ShaharPrishMSFT** [NuGetPackageExplorer/NuGetPackageExplorer#1089] opened 2020-08-19 08:46 UTC
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**:5.7.113+71e0f035d8

**OS version**: Windows 10 latest

**Installed from**: Microsoft Store 

In case of a BUG:

- What is the current result?
Yellow bar at the bottom saying feed failed to load.

- What is the expected result?
Let me put in my credentials again.

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).

- Are there any workarounds? no
- Is there a version in which it did work?
No idea
- Is there a package on Nuget.org which shows the bug?

**Comment by campersau** [comment] 2020-08-19 09:38
Did you check the "stay logged in" checkbox? Then it is by design see https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/1045#issuecomment-648688468
Otherwise it should work (as it does on my machine).

**Comment by 304NotModified** [comment] 2021-02-28 01:45
I assume this is fixed with the comment of @campersau , so closing this.

**Closed by 304NotModified** 2021-02-28 01:45 UTC
