### ISSUE TITLE
Duplicated files are not displayed

### ISSUE THREAD

**Issue by ltrzesniewski** [NuGetPackageExplorer/NuGetPackageExplorer#865] opened 2019-11-12 09:45 UTC
When a faulty package contains a duplicated file, NPE doesn't show it (FodyCommon.dll in this example):

![image](https://user-images.githubusercontent.com/7913492/68659954-9091c080-0538-11ea-9877-936e422391f9.png)

**Type**: Bug

**NPE version**: 5.5.23

**OS version**: Windows 10 - 1903

**Installed from**: GitHub release

**What is the current result?** The duplicated file is shown only once

**What is the expected result?** The duplicated file should be displayed twice, as in the zip

**Are there any workarounds?** No

**Is there a version in which it did work?** Probably not

**Is there a package on Nuget.org which shows the bug?**

https://www.nuget.org/api/v2/package/Fody/6.0.4

Reported here: https://github.com/Fody/Fody/issues/763

**Comment by wreuel** [comment] 2021-03-20 20:35
@clairernovotny how could I help with this issue?

**Comment by clairernovotny** [comment] 2021-03-20 21:49
Go for it. What happens when NuGet restores the package? Only one of the files could be on the disk.

**Comment by ltrzesniewski** [comment] 2021-03-22 13:22
I just checked, and `dotnet restore` does not detect this issue (as of the SDK v5.0.201). One of the two files is written to the disk.

**Comment by clairernovotny** [comment] 2021-03-22 13:30
@jondouglas should NuGet pack error out on this condition? seems like it would always lead to an ambiguous result.

**Comment by JonDouglas** [comment] 2021-03-22 13:35
Pretty sure we just added an error for this last month. Let me look.

**Comment by JonDouglas** [comment] 2021-03-22 15:30
https://github.com/NuGet/NuGet.Client/pull/3923

**Comment by jzabroski** [comment] 2021-07-19 17:39
@JonDouglas  Thank you!   Is it deployed yet.  I dont get an error when I run `dotnet.exe pack` with a scenario that causes this.

@clairernovotny I will say, I do think the basic premise of a NugetPackageExplorer should be that it handle bad zip files with duplicate contents, since the whole point is to see how the zip file is laid out in Nuget-land.

**Comment by jzabroski** [comment] 2021-07-19 17:43
Note, it also looks like this problem can occur as a result of https://github.com/NuGet/Home/issues/3584

**Comment by jzabroski** [comment] 2021-07-19 17:54
@JonDouglas I looked at the warning in https://github.com/NuGet/NuGet.Client/pull/3923 and its not exactly optimal, since it tells you sort of what we already know - that there is a duplicate inside the package.  Would be nicer if `dotnet.exe pack` warns you as its about to add the duplicate what the provenance of both the duplicate and original file was.

I'll guess I'll try MSBuild Bin Log viewer tool from Kirill Osenkov.

**Comment by jzabroski** [comment] 2021-07-19 18:46
Actually, I don't understand how this duplicate detection logic works.

**Comment by jzabroski** [comment] 2021-07-19 19:31
It also looks like there is no way to disable this logic.

I think the problem is that the order in which duplicates is removed from PackageFiles is incorrect, and so there are scenarios in which it is impossible to remove a PackageFiles value from the Pack Task.  This is something I (believe I) noticed a few weeks ago when trying Nugetizer for the first time.

**Comment by jzabroski** [comment] 2021-07-19 20:03
I figured it out - the duplicate detection occurs even when the nuspec file itself contains overlapping entries.   I was assuming the duplicate camed from MSBuild csproj being packed, rather than the nuspec file.

**Comment by clairernovotny** [comment] 2021-08-14 12:06
Closing as by design then.

**Closed by clairernovotny** 2021-08-14 12:06 UTC
Labels: bug, help wanted, wontfix, up-for-grabs
