### ISSUE TITLE
After update to new version, I cannot save the package - receive the error "in use"

### ISSUE THREAD

**Issue by elutsky** [NuGetPackageExplorer/NuGetPackageExplorer#104] opened 2016-05-30 10:27 UTC
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Bug**

**Version: 3.15.0.0**

**Installed from**: ClickOnce as update for prev.version

When trying to Open and save (even without changes) same nuget package, I am receiving the following error:

Error message:
---------------------------
NuGet Package Explorer
---------------------------
The process cannot access the file 'C:\projects\logger\Nuget Packages\eToro.Logger.1.3.3.nupkg' because it is being used by another process.
---------------------------
OK   
---------------------------

This version of nuget package was created and successfully saved and updated with prev. version of nuget package manager.

**Comment by 304NotModified** [comment] 2016-05-30 21:39
Thanks for the report. This is a duplicate of https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/97

Had no time to fix it.

**Closed** 2016-05-30 22:25 UTC
Labels: duplicate
