### ISSUE TITLE
Not able to access V3 feed

### ISSUE THREAD

**Issue by pemo11** [NuGetPackageExplorer/NuGetPackageExplorer#223] opened 2017-08-21 10:38 UTC
I am not able to acccess the following  feed:

https://powershell.myget.org/F/powershell-core/api/v3/index.json

The reason is probably that the Nuget Package Explorer does not Support V3 feeds.

Are there any plans to include this? I know that Package Explorer is not under develoment at the moment but since its such a valuable tool that might change in the future.

**Comment by 304NotModified** [comment] 2017-08-21 11:31
Unfortunately there aren't plans to develop this feature.

**Comment by onovotny** [comment] 2018-01-22 14:16
Closing as a duplicate of #50

**Closed by onovotny** 2018-01-22 14:16 UTC
Labels: duplicate, help wanted, up-for-grabs
