### ISSUE TITLE
Crash when publishing the package to the server

### ISSUE THREAD

**Issue by ameriles** [NuGetPackageExplorer/NuGetPackageExplorer#125] opened 2016-08-24 13:47 UTC
**\- Bug**
**\- 3.18**
**\- ClickOnce**

In case of a BUG:
- What is the current result? 
  **Crash**
- What is the expected result? 
  **Publish the selected package**
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
  Steps to reproduce the bug:
- Open the program
- Open a saved package definition
- Update info
- Publish
- Open another package
- Update info
- Go to FILE->Save
- Go to FILE->Publish. The software will crash

Exception Details
System.IO.InvalidDataException was unhandled
Message: An unhandled exception of type 'System.IO.InvalidDataException' occurred in WindowsBase.dll
Additional information: Se encontraron datos no válidos al descodificar.
- Are there any work arrounds? 
  **yes**
- Is there a version in which it did worked? 
  **Don't know**
- Is there a package on Nuget.org which shows the bug?
  **No specifically**

**Comment by kfrancis** [comment] 2016-11-02 16:11
Happens with 100% consistency for me. Some additional info:

Event log:
```
Faulting application name: NuGetPackageExplorer.exe, version: 3.19.0.0, time stamp: 0x5810b968
Faulting module name: KERNELBASE.dll, version: 10.0.14393.321, time stamp: 0x57f4c291
Exception code: 0xe0434352
Fault offset: 0x000da6f2
Faulting process id: 0x2c9c
Faulting application start time: 0x01d2352361ab7c59
Faulting application path: C:\Users\kfrancis\AppData\Local\Apps\2.0\KVTRY2AV.6TC\9E57QY5H.DMW\nuge..tion_0000000000000000_0003.0013_ded849a462f9d478\NuGetPackageExplorer.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 1e7a36a3-944c-46fc-beb2-985c2cf8562b
Faulting package full name: 
Faulting package-relative application ID: 
```

Stack Trace:
```
Application: NuGetPackageExplorer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.InvalidDataException
   at System.IO.Compression.Inflater.DecodeUncompressedBlock(Boolean ByRef)
   at System.IO.Compression.Inflater.Decode()
   at System.IO.Compression.Inflater.Inflate(Byte[], Int32, Int32)
   at System.IO.Compression.DeflateStream.Read(Byte[], Int32, Int32)
   at MS.Internal.IO.Packaging.DeflateEmulationTransform.Decompress(System.IO.Stream, System.IO.Stream)
   at MS.Internal.IO.Packaging.CompressEmulationStream..ctor(System.IO.Stream, System.IO.Stream, Int64, MS.Internal.IO.Packaging.IDeflateTransform)
   at MS.Internal.IO.Packaging.CompressStream.ChangeMode(Mode)
   at MS.Internal.IO.Packaging.CompressStream.Seek(Int64, System.IO.SeekOrigin)
   at MS.Internal.IO.Zip.ProgressiveCrcCalculatingStream.Seek(Int64, System.IO.SeekOrigin)
   at MS.Internal.IO.Zip.ZipIOModeEnforcingStream.Read(Byte[], Int32, Int32)
   at System.IO.Stream.InternalCopyTo(System.IO.Stream, Int32)
   at System.IO.Stream.CopyTo(System.IO.Stream)
   at NuGet.PackageBuilder.CreatePart(System.IO.Packaging.Package, System.String, System.IO.Stream)
   at NuGet.PackageBuilder.WriteFiles(System.IO.Packaging.Package)
   at NuGet.PackageBuilder.Save(System.IO.Stream)
   at PackageExplorerViewModel.PackageHelper.SavePackage(NuGet.IPackageMetadata, System.Collections.Generic.IEnumerable`1<NuGet.IPackageFile>, System.String, Boolean)
   at PackageExplorerViewModel.PackageViewModel.GetCurrentPackageTempFile()
   at PackageExplorerViewModel.PublishPackageViewModel..ctor(PackageExplorerViewModel.MruPackageSourceManager, NuGetPackageExplorer.Types.ISettingsManager, PackageExplorerViewModel.PackageViewModel)
   at PackageExplorerViewModel.PackageViewModel.PublishExecute()
   at PackageExplorerViewModel.RelayCommand.Execute(System.Object)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at PackageExplorer.App.Main()
```

**Comment by kfrancis** [comment] 2016-11-02 16:28
In my case, I was specifically: opening a nupkg, removing dependencies completely, saving then attempting to publish. Crash. I can open it back up (as the save seems to complete, even though the stack trace might indicate it doesn't) and then publish.

**Comment by 304NotModified** [comment] 2016-11-02 17:55
"Save as"  does work?

**Comment by kfrancis** [comment] 2016-11-02 18:16
@304NotModified Seems to, after the crash - opening the same package is correct, the Date Modified is correct, etc.

**Comment by 304NotModified** [comment] 2016-11-02 18:42
Is that a yes or no ;)

**Comment by kfrancis** [comment] 2016-11-02 18:44
Yes, it does.

Publishing after a save is what crashes.

**Comment by ameriles** [comment] 2016-11-02 19:47
The workaround that I use is to use "Save As".

**Comment by 304NotModified** [comment] 2016-12-28 15:52
> Message: An unhandled exception of type 'System.IO.InvalidDataException' occurred in WindowsBase.dll
> Additional information: Se encontraron datos no válidos al descodificar.

Se encontraron datos no válidos al descodificar = Invalid data was found when decoding.

**Comment by 304NotModified** [comment] 2016-12-28 22:15
Too bad I cannot reproduce this. 

Is this still an issue in 3.21? (will be released today)

**Comment by 304NotModified** [comment] 2016-12-28 22:25
3.21 is live! Please retest - thanks!

**Comment by 304NotModified** [comment] 2017-03-02 22:55
Closing this due to inactivity. Please let us know if this still an issue and please provide the requested info.

**Closed by 304NotModified** 2017-03-02 22:55 UTC
Labels: bug, can't reproduce
