### ISSUE TITLE
application unexpectedly close

### ISSUE THREAD

**Issue by inouefumina** [NuGetPackageExplorer/NuGetPackageExplorer#718] opened 2019-06-11 11:12 UTC
Hi, from Tokyo.

the problem is that i downloaded one online package and succeeded but i cannot open that package through Nuget package Explorer.
When i click the line of that certain package in the file of my PC, only one second the application open but in the next second it automatically close.

At the end i want to use that package inside Uipath, and i used Nuget package explorer just for downloading the package in the Nuget form.

please tell me how i can solve this problem.

thank you.

**Comment by campersau** [comment] 2019-06-11 11:33
possibly duplicate of #716

**Comment by campersau** [comment] 2019-06-11 12:29
Can you please try out the new version 5.2.49?
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/716#issuecomment-500812335

**Comment by onovotny** [comment] 2019-06-15 16:45
Closing as a dup. Please re-open if it happens with 5.2.49

**Closed by onovotny** 2019-06-15 16:45 UTC
