### ISSUE TITLE
Why does PDB checksum validation fail the Source Link and Deterministic checks?

### ISSUE THREAD

**Issue by bording** [NuGetPackageExplorer/NuGetPackageExplorer#1000] opened 2020-05-28 20:58 UTC
**Type** Question / feature request
**NPE version**: 5.7.27
**OS version**: Windows 10 1909 - 18363.836
**Installed from**: Microsoft Store

Ever since NuGet Package Explorer added PDB checksum validation, our packages have been showing up as not having Source Link support despite being properly indexed:

![image](https://user-images.githubusercontent.com/753669/83191815-a5aff480-a102-11ea-8b8f-b61394bfcfd5.png)

It's failing because of the checksum validation: 

![image](https://user-images.githubusercontent.com/753669/83191938-ca0bd100-a102-11ea-981c-33e0498f02e9.png)

The package used in the screen shots: [NServiceBus 7.3.0](https://www.nuget.org/packages/NServiceBus/7.3.0)

However, despite that, Source Link works fine on our packages, letting you step in to code as expected.

We do use Fody for post-processing of the assemblies, and it appears that it is removing the `PdbChecksum` `DebugDirectoryEntry` from the PDB when it does. While I am going to see if there's a way to get Fody to write a valid checksum value into the PDB, I think it makes sense to change the way NuGet Package Explorer handles this scenario.

What does the checksum validation have to do with Source Link? It seems to me that it should be a separate entry if you want to report that.

I also think that the deterministic check should not by skipped in this scenario. It currently fails because of "Missing Symbols", which also isn't true in this case.

**Comment by clairernovotny** [comment] 2020-05-28 21:04
The checksum is there to ensure that the pdb matches the dll, which is important for debugging and traceability. The fact that it works is likely an accident....  @tmat, any thoughts here?

**Comment by bording** [comment] 2020-05-28 21:12
In this case, it's not that the checksum doesn't match, it's the PDB doesn't have a checksum entry at all.

**Comment by clairernovotny** [comment] 2020-05-28 21:19
I believe that's an invalid PDB then.

**Comment by bording** [comment] 2020-05-28 21:25
> I believe that's an invalid PDB then.

Except it works fine in every case that I can think of. If the VS debugger can use it successfully, Source Link works, etc. what is invalid about it?

**Comment by clairernovotny** [comment] 2020-05-28 21:29
I just talked to @tmat. In this case, when the pdb is in the nupkg, it looks like the checksum isn't needed. I can fix the logic to account for that.

*However* snupkg requires the checksum for things to match and work so there's still an issue that needs to be fixed in Fody.

**Comment by clairernovotny** [comment] 2020-05-28 21:49
@simoncropp you may want to take a look at this 👆

**Comment by bording** [comment] 2020-05-28 21:49
Thanks for checking on this! I'll pursue getting this fixed in Fody.

We don't publish snupkgs, and don't currently have any plans to do so. However, while testing this, I noticed that a `netcoreapp3.1` app can no longer find PDBs in a NuGet package like a `netcoreapp2.1` app can, so that's a regression. :cry:

After my issue to try to get that fixed for .NET Framework apps has never been addressed, I'm not opmtisimic of my chance to get that change for .NET Core 3.x!

I suppose I'd switch to embedded PDBs before going with snupkgs, though.

**Comment by clairernovotny** [comment] 2020-05-28 21:50
Do you have a repro of that not finding pdb's issue?

**Closed** 2020-05-28 21:56 UTC
Labels: bug

**Comment by bording** [comment] 2020-05-28 21:57
It was just a basic console app with the NServiceBus package referenced. I tried to step into the code, and it didn't work. I checked the Modules view in VS, and it showed no PDB loaded. The same console app running on 2.1 found the PDB in the NuGet folder and worked fine.

 I can get something put together for you if you want.

**Comment by clairernovotny** [comment] 2020-05-28 22:00
Please. Also if you can do that and use the "Report a Problem" feature in VS repro there and send me the link, that'll help too.

**Comment by tmat** [comment] 2020-05-28 23:25
See https://github.com/dotnet/sdk/issues/1458

**Comment by SimonCropp** [comment] 2020-05-28 23:27
@tmat that is not the problem here. NSB is correctly bundling pdbs in the package

**Comment by tmat** [comment] 2020-05-28 23:29
The problem is that the PDBs are not copied from the package cache to the output directory.

**Comment by SimonCropp** [comment] 2020-05-28 23:30
@tmat  sorry. yep. deleted my comment after re-reading the issue

**Comment by bording** [comment] 2020-05-29 18:09
@clairernovotny Looking at https://github.com/dotnet/sdk/issues/3161#issuecomment-635677944, it seems like https://github.com/dotnet/sdk/issues/1458 is intended to cover the problem I was talking about for .NET Core as well.

Based on that, do you think I still need to worry about a separate repro?

**Comment by bording** [comment] 2020-05-29 18:11
Regarding Fody causing the checksum to be removed, it looks like it's a Mono.Cecil problem: https://github.com/jbevain/cecil/issues/610
