### ISSUE TITLE
Support publishing to servers that require authentication

### ISSUE THREAD

**Issue by timothyparez** [NuGetPackageExplorer/NuGetPackageExplorer#92] opened 2016-04-18 06:46 UTC
![image](https://cloud.githubusercontent.com/assets/2060470/14595676/cf06f6aa-0573-11e6-839e-461d281d67da.png)

**Type** (choose one):
- Feature request

**NPE version**: 3.14.0.0

**Installed from**: ClickOnce

in case of a FEATURE REQUEST:
 
 - Why do we need it?
   Because some feeds require authentication.
 - Please provide an use case.
    We have private feeds hosted with NuGet.Server running on IIS with basic authentication enabled  
    While the API key prevents unauthorized people from pushing packages, the authentication
    prevents unauthorized people from fetching  packages.

Related to: Issue #58

**Comment by 304NotModified** [comment] 2016-04-24 21:56
This is the same as #58? (not only related)?

**Comment by 304NotModified** [comment] 2016-06-21 21:35
Duplicate of https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/58

**Closed by 304NotModified** 2016-06-21 21:35 UTC
Labels: duplicate, feature

**Comment by pantonis** [comment] 2016-11-24 16:20
Was this implemented?

**Comment by 304NotModified** [comment] 2016-11-24 16:25
nope

**Comment by pantonis** [comment] 2016-11-24 16:26
so there is not anyway to publish to a windows authenticated nuget server?

**Comment by 304NotModified** [comment] 2016-11-24 16:26
but there is https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/140, if you could test that one.

I don't have a feed which needs auth, so hard to test.

**Comment by 304NotModified** [comment] 2016-11-24 16:26
> so there is not anyway to publish to a windows authenticated nuget server?

If you own the same domain, it should work

**Comment by pantonis** [comment] 2016-11-24 16:29
I just tried the http://user:pwd@feedUrl

Still getting Unauthorised. Checked the url in browser and it opens without any problem

**Comment by 304NotModified** [comment] 2016-11-24 18:11
did you tested the pull request ? (so build it yourself)?

**Comment by 304NotModified** [comment] 2016-11-24 18:12
mmm 

> just tried the http://user:pwd@feedUrl

this isn't windows Auth. This is Basic auth. So won't work
