### ISSUE TITLE
Chocolatey shows errors when installing (non-breaking)

### ISSUE THREAD

**Issue by 304NotModified** [NuGetPackageExplorer/NuGetPackageExplorer#158] opened 2017-01-01 22:06 UTC
See screenshot. 

![image](https://cloud.githubusercontent.com/assets/5808377/21583210/f1205960-d076-11e6-9c44-235daa7bbbc8.png)

![image](https://cloud.githubusercontent.com/assets/5808377/21583211/f48894be-d076-11e6-84d4-a72589ae52c3.png)

Discussed in short in https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/142

**Comment by PatrickKalkman** [comment] 2017-04-07 17:34
Did some investigation and the rows that contain Start-ChocolateyProcessAsAdmin in ChocolateyInstall.ps1 seem to cause these errors. Strangely enough the file association is created.
I am going to further investigate this issue.

**Comment by 304NotModified** [comment] 2017-04-07 17:39
ah would be great if we could fix this!

**Comment by PatrickKalkman** [comment] 2017-04-08 09:01
It seems to be a problem with the powershell script Start-ChocolateyProcessAsAdmin.ps1. If I use Install-ChocolateyFileAssociation which uses Start-ChocolateyProcessAsAdmin internally, I get the same result. I created an issue with the chocolatey project (https://github.com/chocolatey/choco/issues/1244). Maybe they can fix it.

**Comment by 304NotModified** [comment] 2017-04-08 09:53
Great work, thanks!

**Comment by ferventcoder** [comment] 2017-04-10 08:37
Howdy folks - it's not an error. It's just that the stream logs to stderr instead of stdout.

**Comment by PatrickKalkman** [comment] 2017-04-10 10:41
Thanks for the feedback @ferventcoder. Is it going to be changed? It still feels somewhat strange all these red messages scrolling on the screen during an installation.

**Comment by 304NotModified** [comment] 2017-04-10 16:08
or could be prevent this, by  using `install-ChocolateyFileAssociation > > $null` ?

**Comment by ferventcoder** [comment] 2017-04-11 17:18
@PatrickKalkman that's the hope - the problem is it is PowerShell doing this, not Chocolatey.

**Comment by ferventcoder** [comment] 2017-04-11 17:19
So we will be looking for a workaround - we thought we had a good way of doing this for 0.10.4, but we quickly released 0.10.5 to put it back to old way since it was clear our workaround was completely broken in some cases.

**Comment by ferventcoder** [comment] 2017-08-27 20:58
https://github.com/chocolatey/choco/issues/1016 is the issue associated with this.

**Comment by onovotny** [comment] 2018-01-21 01:08
Also likely related: https://github.com/chocolatey/chocolatey-licensed-issues/issues/35

**Comment by onovotny** [comment] 2018-01-21 01:10
I'm going to close this as external for now. If there's anything we need to change in our install script, please reopen.

**Closed by onovotny** 2018-01-21 01:10 UTC
Labels: chocolatey, external, install error
