### ISSUE TITLE
non pre-release package is not showing unless pre-release is check

### ISSUE THREAD

**Issue by satuday** [NuGetPackageExplorer/NuGetPackageExplorer#810] opened 2019-08-12 19:27 UTC
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**Type** (choose one):

- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)
NuGet Package Explorer - Store - (5.2.88+dfa83d6fbf)
**OS version**: (Windows 7, 10 - 1803/17134, etc)
window 10
**Installed from**: Microsoft Store / Chocolatey.org / Zip on GitHub / CI channel
MS store
In case of a BUG:

- What is the current result?
non pre release package is not showing in result unless pre-release check box is checked
- What is the expected result?
all non pre release package should show in result if pre-release is not checked
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions).
- Are there any workarounds? yes/no
Always check show pre release packages

**Comment by onovotny** [comment] 2019-08-12 19:30
Hi,

Just to confirm, when you search for packages, only stable ones show up if the `pre-release` box is unchecked?

If so, that's by design. The `pre-release` checkbox must be checked to see pre-release packages in the search results. 

If it's something else, please let me know.

**Comment by satuday** [comment] 2019-08-12 19:57
no, some stable pkg is not showing up when pre-release is not checked.

**Comment by onovotny** [comment] 2019-08-12 20:00
That would be a bug -- do you have an example package/version we can take a look at?

**Comment by satuday** [comment] 2019-08-12 20:35
unfortunately I'm seeing this issue on our internal nuget repository using jfrog artifactory and unable to reproduce in public nuget repository.  I tried a few pkg in nuget.org and dont seem to have this issue.  
I'd tried using visual studio nuget manager and all stable version pkg is shown on the result when include prerelease is not check.  But when I search for the same package in nuget package explorer, the stable package is not shown in the result when show pre-release is not check.

**Comment by satuday** [comment] 2019-08-12 21:30
Hi, after some more testing, I think the issue might cause by our internal nuget repo and not with the app.

**Comment by 304NotModified** [comment] 2019-08-13 21:12
Then I think we could close this one as there is no action for us here :)

**Closed by 304NotModified** 2019-08-13 21:12 UTC
