### ISSUE TITLE
Save errors

### ISSUE THREAD

**Issue by eschneider999** [NuGetPackageExplorer/NuGetPackageExplorer#310] opened 2018-01-03 10:20 UTC
Take me 5 times longer to make a package because the save does not work.
I must save, close, open, redo, open, close, save, bla bla bla

One thing I have noticed is it has something to do with add/remove of folders and files.

- Bug

3.24.0.0

Windows Store

In case of a BUG:

- What is the current result?
- What is the expected result? work
- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions) Maybe you should provide that?????
- Are there any work arrounds? no
- Is there a version in which it did worked? seen before
- Is there a package on Nuget.org which shows the bug?

**Comment by 304NotModified** [comment] 2018-01-03 13:44
please fill in the template

**Comment by 304NotModified** [comment] 2018-01-03 13:44
duplicate of https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/309

**Closed by 304NotModified** 2018-01-03 13:44 UTC
