### ISSUE TITLE
Cannot build out of the box

### ISSUE THREAD

**Issue by matyasforian** [NuGetPackageExplorer/NuGetPackageExplorer#358] opened 2018-02-23 09:50 UTC
When I clone and try to build the project (either in Visual Studio or via the build.cmd) the build fails with errors that the class PackageExplorer.Resources is missing. 

To solve it I had to right click Resources.resx, click Properties and here set Custom Tool namespace to  "PackageExplorer.Resources" 

I guess you forgot to check this setting in to the .csproj file?

**Comment by onovotny** [comment] 2018-02-23 13:11
All of the files are checked in. What version of VS are you using? Do you have automatic package restore enabled? The resx files get set by targets that come down during restore.

**Comment by svick** [comment] 2018-02-23 13:14
As far as I can tell, this was caused by https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/commit/6531156bbb8f2cfeb6331db4e09d161020e33506. I have just created https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/360, which should fix this.

**Comment by matyasforian** [comment] 2018-02-23 13:47
Yep, setting CustomToolNamespace in the csproj file fixes it.

**Closed** 2018-02-23 20:49 UTC
