### ISSUE TITLE
Failed to connect to remote feed (failed with 401)

### ISSUE THREAD

**Issue by elutsky** [NuGetPackageExplorer/NuGetPackageExplorer#214] opened 2017-07-30 15:58 UTC
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

**BUG**

**NPE version**: (e.g. 3.12) (see Help -> about): 3.21.0.0

**Installed from**: ClickOnce 

When I am trying to connect to private feed, I am failed with 401 exception.
No additional logs found.

Also, I am connected to the same feed in Visual Studio (2015), and has this source listed in nugget.config

Can you please to shade some light and provide some documentation about steps for connecting to the private repo and ways to investigate them (like, logs location, ....)?

Thanks!

**Comment by 304NotModified** [comment] 2017-07-30 22:22
Currently (basic) authentication is not implemented, so I guess that's the issue here?

**Comment by elutsky** [comment] 2017-07-31 03:26
My private feeds (VSTS)  not actually using basic authentication.

I was waiting NPE to prompt to complete auth....

**Comment by elutsky** [comment] 2017-07-31 03:30
Sorry, seems to be subcase of #122

**Comment by elutsky** [comment] 2017-07-31 03:32
Can u pls in 2 words to point me out where I should start to dig from in the code?

Thanks

**Comment by 304NotModified** [comment] 2017-11-17 21:35
duplicate of https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/214

**Closed by 304NotModified** 2017-11-17 21:35 UTC

**Comment by 304NotModified** [comment] 2017-11-21 23:00
@elutsky sorry for the late reply.

PushPackage and DeletePackageFromServer are good starts  (in the `GalleryServer` class)
