### ISSUE TITLE
Hard crash on abnormal color profile

### ISSUE THREAD

**Issue by Starz0r** [NuGetPackageExplorer/NuGetPackageExplorer#1105] opened 2020-09-11 05:33 UTC
**Type**: Bug

**NPE version**: 5.7.145

**OS version**: Windows 10 - Redstone 7 / 1909

**Installed from**: Chocolatey.org

Opening packages containing an icon larger than 1024x1024 will crash the application on launch. Actually I don't know if it has to be larger than 1024x1024, I'm just guessing, at this point it could be an image larger than 512x512. The package I tested this on crashed at 2048x2048, even though the file is a mere 172 KB. There is also no exception notification window, which is odd.

For context, I tried opening this package: https://chocolatey.org/packages/legendary/0.0.1

**Comment by campersau** [comment] 2020-09-13 12:58
Exception (in german...):
```
System.IO.FileFormatException
  HResult=0x80131537
  Message=Der Bitmap-Farbkontext ist ungültig.
  Source=PresentationCore
  StackTrace:
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.ColorConvertedBitmap..ctor(BitmapSource source, ColorContext sourceColorContext, ColorContext destinationColorContext, PixelFormat format)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.OnDownloadCompleted(Object sender, EventArgs e)
   at System.Windows.Media.UniqueEventHelper.InvokeEvents(Object sender, EventArgs args)
   at System.Windows.Media.Imaging.LateBoundBitmapDecoder.DownloadCallback(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at PackageExplorer.PackageChooserDialog.ShowDialog(String searchTerm) in C:\dev_projects\NuGetPackageExplorer\PackageExplorer\PackageChooser\PackageChooserDialog.xaml.cs:line 152

Inner Exception 1:
COMException: Das angegebene Farbprofil ist ungültig. (0x800707DB)
```

**Comment by Starz0r** [comment] 2020-09-13 13:32
> COMException: Das angegebene Farbprofil ist ungültig. (0x800707DB)

Looks like it's related to the color profile and not the icon size.

**Comment by campersau** [comment] 2020-09-13 13:34
The issue is this line. Removing it resolves the issue:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/4da26d5ea2e6f1af0fda767236552f47672c041f/PackageExplorer/Converters/IconUrlToImageCacheConverter.cs#L64-L66

But it also exists in NuGet.Client PackageManagement UI but there it does not crash...
https://github.com/NuGet/NuGet.Client/blob/0df34003a113462cfa02e369491180686a08beaa/src/NuGet.Clients/NuGet.PackageManagement.UI/Converters/IconUrlToImageCacheConverter.cs#L156-L158

**Comment by clairernovotny** [comment] 2020-09-13 13:51
@campersau Keep in mind that VS is running on .NET Framework and we're on .NET Core. Might be the difference somewhere underneath.

**Comment by campersau** [comment] 2020-09-13 14:18
Hmm after testing it a bit more VS now also crashes with the same exception, wired... Not sure why it worked the first time I tried it in VS.

Steps to reproduce in VS:
- Open VS Manage NuGet Packages
- Add `https://chocolatey.org/api/v2/` feed
- Search for `legendary`
- VS crashes with the same exception

Code to reproduce in WPF app (Core / Framework):
```c#
var bitmap = new BitmapImage();
bitmap.BeginInit();
bitmap.UriSource = new Uri("https://cdn.statically.io/gh/Starz0r/ChocolateyPackagingScripts/2055976c/assets/legendary.png");
bitmap.DecodePixelWidth = 32;
bitmap.EndInit();
// set source of an <Image>
image.Source = bitmap;
```

I think instead of throwing the exception it should be passed into `DecodeFailed` which it currently isn't. Going to open an issue in dotnet/wpf.

**Comment by clairernovotny** [comment] 2020-09-16 16:00
> Hmm after testing it a bit more VS now also crashes with the same exception, wired... Not sure why it worked the first time I tried it in VS.
> 
> Steps to reproduce in VS:
> 
> * Open VS Manage NuGet Packages
> * Add `https://chocolatey.org/api/v2/` feed
> * Search for `legendary`
> * VS crashes with the same exception
> 
> Code to reproduce in WPF app (Core / Framework):
> 
> ```cs
> var bitmap = new BitmapImage();
> bitmap.BeginInit();
> bitmap.UriSource = new Uri("https://cdn.statically.io/gh/Starz0r/ChocolateyPackagingScripts/2055976c/assets/legendary.png");
> bitmap.DecodePixelWidth = 32;
> bitmap.EndInit();
> // set source of an <Image>
> image.Source = bitmap;
> ```
> 
> I think instead of throwing the exception it should be passed into `DecodeFailed` which it currently isn't. Going to open an issue in dotnet/wpf.

What version of VS crashes for you?

**Comment by campersau** [comment] 2020-09-17 08:03
@clairernovotny I have tried:
- Microsoft Visual Studio Enterprise 2019 Version 16.7.3
- Microsoft Visual Studio Enterprise 2019 Preview Version 16.8.0 Preview 3.0

Screenshot from the nuget package sources in VS:
![image](https://user-images.githubusercontent.com/4009570/93437820-b7ddba80-f8cc-11ea-96bf-7577199e1ad1.png)

Here a little video: [VS_chocolatey_legendary_crash.zip](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/files/5237275/VS_chocolatey_legendary_crash.zip)

FYI: I will try out the things mentioned in https://github.com/dotnet/wpf/issues/3503 over the weekend.

**Comment by miloush** [comment] 2020-09-17 08:33
I think anyone being able to supply an image that crashes VS should be a good case to get this fixed in WPF, including .NET Framework.

**Comment by campersau** [comment] 2020-09-19 09:50
There are two workarounds for this issue (until https://github.com/dotnet/wpf/issues/3503 gets fixed):

1. Use `CreateOptions = BitmapCreateOptions.IgnoreColorProfile`
I haven't found images where this would make a huge difference yet.

2. Don't set `DecodePixelWidth`
This has a greater effect in that now the original image is shown instead of a scaled down one.
Here is a small list of images before and after:
![image](https://user-images.githubusercontent.com/4009570/93662990-a4655780-fa64-11ea-9cc4-ac07869f47e5.png)

Here are the memory profiles for these two options.
1. Original (current)
2. IgnoreColorProfile
3. Don't set DecodePixelWidth

The snapshots were taken:
1. After start
2. After opening package search
3. After scrolling down 10 times
4. After refreshing

Managed Heap:
![image](https://user-images.githubusercontent.com/4009570/93664151-15107200-fa6d-11ea-86ac-79fbd2bee2b9.png)

Heap:
![image](https://user-images.githubusercontent.com/4009570/93664159-25c0e800-fa6d-11ea-8d30-3102d273f400.png)

So I would go for the first option IgnoreColorProfile.

**Comment by miloush** [comment] 2020-09-19 11:35
Cool, just to clarify, all the options still have your additional caching of BitmapImages, correct? That would explain the twice as much memory usage....

**Comment by miloush** [comment] 2020-09-19 12:01
Since you are doing your own caching, have you tried using `BitmapCacheOptions.None` when loading the image?

**Comment by campersau** [comment] 2020-09-19 12:34
Yes, the additional caching is still active.

I have tried `BitmapCacheOptions.None` and also removed our own caching but it uses similar memory in all scenarios.
I guess it is because the `BitmapImage` instance is the same in both caches.
So for me it looks like `DecodePixelWidth` reduces memory consumption.

**Closed** 2020-09-19 16:10 UTC
