### ISSUE TITLE
Publish Key locked when trying to publish to local host with API Key

### ISSUE THREAD

**Issue by styxtraveler** [NuGetPackageExplorer/NuGetPackageExplorer#346] opened 2018-02-16 13:45 UTC
Hi! Thanks for reporting this feature/bug/question! 

Please keep / fill in the relevant info from this template so that we can help you as best as possible.

-Bug

**Version: 4.0.12 +g90e2a8eofd
**Installed from**: Windows Store

In case of a BUG:

- When trying to publish a package to a different Publish URl using an API Key The Publish button is disabled. 

- Expecting that the button would not be disabled. 

- Please post full exception details in case of an Exception (message, stacktrace, inner exceptions)
- Are there any work arrounds? yes
  if you click the credentials radio button, and enter credentials. (doesn't matter what credentials) and click publish. The button unlocks. The button remains unlocked when you click back to API key and after publishing, it retains the api key and the url and works as desired. 

- Is there a version in which it did worked? yes. all previous versions. 
- Is there a package on Nuget.org which shows the bug?  not that I'm aware of.

**Comment by campersau** [comment] 2018-02-16 14:40
Looks like a duplicate of https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/331

**Comment by PandeleFlorin** [comment] 2018-02-16 16:00
It happens to me too, with some company-specific nuget repository (NOT localhost). Looks like a simple validation bug that should be fixed immediately.

**Comment by buddwright** [comment] 2018-02-16 17:59
Can confirm this also occurs with packages that were working as of yesterday, to a company-specific nuget repository. As of today the Publish button never enables when putting in our API key.

**Comment by onovotny** [comment] 2018-02-18 03:19
Can you please try the latest Nightly build and see if it's fixed there? I will aim to get 4.1 to the store ASAP, though the store takes several days to publish.

**Comment by onovotny** [comment] 2018-02-21 18:23
Fixed in 4.1

**Closed by onovotny** 2018-02-21 18:23 UTC
Labels: duplicate
