### ISSUE TITLE
Package using PackageLicenseFile should not link to aka.ms/deprecateLicenseUrl

### ISSUE THREAD

**Issue by svick** [NuGetPackageExplorer/NuGetPackageExplorer#1196] opened 2021-01-12 16:59 UTC
**Type**: Tiny bug

**NPE version**: 5.8.84+a036cdfd62

**OS version**: Windows 10

**Installed from**: Microsoft Store

When you open a package that uses `<license type="file">`, NPE displays the following:

![](https://user-images.githubusercontent.com/287848/104346088-4ec72600-54ff-11eb-8671-6dd0e2ccc196.png)

The problem is that the "View License Terms" link leads to https://aka.ms/deprecateLicenseUrl. As I understand it, `<license type="file">` is the correct way to specify a custom license (e.g. one that is not open source), so I think either clicking the link should open the license file from the package, or the link should not be shown in this situation.

To test this, you can create such package using the following .csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="license.txt" PackagePath="license.txt" Pack="true"/>
  </ItemGroup>

</Project>
```

**Comment by michael-hawker** [comment] 2021-02-23 19:23
I believe this is a duplicate of #864? But this has more details about what the problem is (screenshot).

I just hit this trying to validate the transition of the Windows Community Toolkit packages.

**Closed** 2021-08-14 12:04 UTC
Labels: enhancement, help wanted, up-for-grabs
