### ISSUE TITLE
Unable to open content

### ISSUE THREAD

**Issue by JamesNK** [NuGetPackageExplorer/NuGetPackageExplorer#632] opened 2019-02-05 20:02 UTC
**Type**: Bug

**NPE version**: 5.0.132+f33e9c233d

**OS version**: Win10

I have a NuGet package that has been unzipped, the content Authenticode signed, rezipped, and then package signed.

I can open the package in NPE but double clicking on any content will fail with an error dialog:

![image](https://user-images.githubusercontent.com/303201/52300687-66c9cd00-29ed-11e9-9c46-5d472c812705.png)

Is this an error with NPE or the package? If it is a package problem then NPE should provide more detail.

The link to the package is in a Twitter DM

**Comment by JamesNK** [comment] 2019-02-05 20:04
cc @jtattermusch

**Comment by onovotny** [comment] 2019-02-08 00:32
Closing as the issue is with the package as noted in the linked issue.

**Closed by onovotny** 2019-02-08 00:32 UTC
