### ISSUE TITLE
OutOfMemoryException with large static json feed

### ISSUE THREAD

**Issue by EgorBo** [NuGetPackageExplorer/NuGetPackageExplorer#764] opened 2019-08-07 09:41 UTC
**Type** (choose one):

- Bug

**NPE version**: (e.g. 5.x) (see Help -> about)
5.2.88+dfa83d6fbf

**OS version**: (Windows 7, 10 - 1803/17134, etc)
Windows 10 x64 1903, 
**Installed from**: Microsoft Store / Chocolatey.org / Zip on GitHub / CI channel
Microsoft Store
In case of a BUG:

Constantly throws OutOfMemoryException for `https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json` feed
![image](https://user-images.githubusercontent.com/523221/62612665-8300e500-b910-11e9-83e5-ca50f30d59cb.png) sometimes it works but mostly just OOM.
RAM: 32 GB, about to 16 is free

Also, search doesn't work

**Comment by campersau** [comment] 2019-08-07 10:06
The OOME should have been fixed by https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/pull/747, but I can also reproduce it if I run the packaged version.
Search for static feeds is tracked here https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/607

**Comment by EgorBo** [comment] 2019-08-07 10:13
@campersau is the fixed version already released? the latest 5.2.90 also OOMs for me

**Comment by EgorBo** [comment] 2019-08-07 10:19
Just built the app from sources and it works but since the search doesn't work in this feed and it loads only 15 elements per pages it makes the app unusable for the feed.

**Comment by 304NotModified** [comment] 2019-08-07 11:13
Yes that will be fixed in #607 as well (first load sill slow, but fast paging)

**Comment by campersau** [comment] 2019-08-07 11:23
The OOME still happens with the **packaged** version. So I would suggest reopening the issue.

![image](https://user-images.githubusercontent.com/4009570/62619081-30c2c280-b916-11e9-93ed-065792630a70.png)

```
   bei Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   bei Newtonsoft.Json.JsonTextReader.ParseValue()
   bei Newtonsoft.Json.JsonTextReader.Read()
   bei Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   bei Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   bei Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   bei NuGet.Protocol.JsonUtility.LoadJson(JsonReader jsonReader) in D:\dev\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Utility\JsonUtility.cs: Zeile37
   bei NuGet.Protocol.JsonUtility.LoadJson(TextReader reader) in D:\dev\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Utility\JsonUtility.cs: Zeile28
   bei NuGet.Protocol.StreamExtensions.<AsJObjectAsync>d__2.MoveNext() in D:\dev\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Utility\StreamExtensions.cs: Zeile30
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei NuGet.Protocol.HttpSource.<>c__DisplayClass16_0`1.<<ProcessStreamAsync>b__0>d.MoveNext() in D:\dev\NuGet.Client\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs: Zeile220
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei NuGet.Protocol.HttpSource.<ProcessResponseAsync>d__18`1.MoveNext() in D:\dev\NuGet.Client\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs: Zeile256
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei NuGet.Protocol.HttpSource.<ProcessStreamAsync>d__16`1.MoveNext() in D:\dev\NuGet.Client\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs: Zeile206
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei NuGet.Protocol.HttpSource.<GetJObjectAsync>d__19.MoveNext() in D:\dev\NuGet.Client\src\NuGet.Core\NuGet.Protocol\HttpSource\HttpSource.cs: Zeile262
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei NuGet.Protocol.RawSearchResourceV3.<SearchPage>d__3.MoveNext() in D:\dev\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Resources\RawSearchResourceV3.cs: Zeile84
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei NuGet.Protocol.RawSearchResourceV3.<Search>d__4.MoveNext() in D:\dev\NuGet.Client\src\NuGet.Core\NuGet.Protocol\Resources\RawSearchResourceV3.cs: Zeile118
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei PackageExplorerViewModel.ShowLatestVersionQueryContext`1.<GetItemsForCurrentPage>d__19.MoveNext() in C:\dev_projects\NuGetPackageExplorer\PackageViewModel\PackageChooser\ShowLatestVersionQueryContext.cs: Zeile69
```

**Comment by 304NotModified** [comment] 2019-08-07 11:26
What is the "packaged version"?

**Comment by campersau** [comment] 2019-08-07 11:32
With `packaged` I mean the `PackageExplorer.Package` project :)

**Comment by onovotny** [comment] 2019-08-07 13:32
Is this an issue with the way we're loading the feed via the NuGet libraries or is this an issue with the NuGet libraries themselves? If it's the latter, we should probably file an issue on the NuGet repo.

**Comment by campersau** [comment] 2019-08-07 13:55
The problem is, that this is a static feed (not search- or pageable) and is ~140MB of json.
This is completly parsed with Newtonsoft.Json in NuGet.Client and results in a OOME (wants to use more than 1GB) in the windows store version. 
Looks like windows store apps don't get much memory ~1GB.

**Comment by onovotny** [comment] 2019-08-07 13:58
I'd be surprised if the package had anything to do with it. We are publishing as a 32-bit app. Does it make a difference if we switch to win-x64?

**Comment by onovotny** [comment] 2019-08-07 14:03
Changes should be here: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/NuGetPackageExplorer.csproj#L13
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/NugetPackageExplorer.nuspec#L28

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer.Package/PackageExplorer.Package.wapproj#L9-L13 (and the sln file that points to the configs)
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer.Package/PackageExplorer.Package.wapproj#L29
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer.Package/PackageExplorer.Package.wapproj#L63

https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/azure-pipelines.yml#L101
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/azure-pipelines.yml#L125

**Comment by campersau** [comment] 2019-08-07 14:27
Looks like switching to x64 works! I will send a PR shortly.

x86:
![image](https://user-images.githubusercontent.com/4009570/62630726-ca4a9e00-b92f-11e9-870f-0cf7f7ceff11.png)

x64:
![image](https://user-images.githubusercontent.com/4009570/62630898-13025700-b930-11e9-974e-fa1ba3ccdcfe.png)

**Comment by onovotny** [comment] 2019-08-07 14:31
I think it's still worth an issue on the NuGet repo as perhaps there's something they can do to improve memory usage with System.Text.Json. 

/cc @rrelyea

**Comment by 304NotModified** [comment] 2019-08-07 15:11
> I think it's still worth an issue on the NuGet repo as perhaps there's something they can do to improve memory usage with System.Text.Json.


I see Newtonsoft.Json in the stack Trace?

**Closed** 2019-08-07 15:34 UTC
